### PR TITLE
Fixed typo in router.d.ts

### PR DESCRIPTION
**Pull request by DAnn2012**
Update router.d.ts

Also fixed typo in Photo Browser KS pages (Core/React/Svelte/Vue), request.js and request.d.ts

### CODE REVIEW

**Comment by DAnn2012** [comment]
https://github.com/framework7io/framework7/blob/69a577c97af9f16d4943a9f4b891cb017eacd3cf/src/core/shared/request.js#L324

@nolimits4web  This **message: xhr.status** is right or should it be **message: xhr.statusText**?

**Comment by nolimits4web** [comment]
@DAnn2012 it was `xhr.status` in before (in v5) but i think `.statusText` has more sense here

**Comment by DAnn2012** [comment]
@nolimits4web So will you make the change after merging this PR?

I also point out that there are some references to **Template7** in this file:

https://github.com/framework7io/framework7/blob/43480d032de6a4804c562ebe1d6fc767f529aca3/kitchen-sink/core/pages/page-loader-component.html#L17-L20

https://github.com/framework7io/framework7/blob/43480d032de6a4804c562ebe1d6fc767f529aca3/kitchen-sink/core/pages/page-loader-component.html#L38

**Comment by nolimits4web** [comment]
Thanks. I've fixed mentioned issue

**Pull request merged**
