### PR TITLE
Update framework7.js

### PR DESCRIPTION
**Pull request by SpiderNeo1**
Added a difference on "distance from side of screen for slide panels swipe" when the slide is open and when it is closed.

### CODE REVIEW

**Comment by J05HI** [comment]
@SpiderNeo1 
Do no modify the dist files. Make your changes in the src folder.

**Comment by SpiderNeo1** [comment]
Ok J05HI. I did it just now.

**Comment by J05HI** [comment]
@SpiderNeo1 
Okay, now @nolimits4web can take a look at it :)

**Comment by ZanderBrown** [comment]
Could you clean this up please? Your PR shouldn't modify anything in the dist folder.

**Comment by SpiderNeo1** [comment]
What should I do ?
I have to modify the file "framework7.js" (dist) again and put it back as before?

**Comment by J05HI** [comment]
@SpiderNeo1 @ZanderBrown 
That should be okay

**Comment by Dhanasekaranjones** [comment]
Older framework 7 js file version is 1.4.0 and chartvar  is presenting in the plugin.
But i have update the framework 7 latest version for 1.6.4
This chartvar cannot support in the latest framework 7 file.

I see the error for **Uncaught ReferenceError: chartvar is not defined**

What's the problem for this error.

**Comment by SpiderNeo1** [comment]
Will there ever be a version 1.67 or 1.7.0 with my add?

**Comment by nolimits4web** [comment]
Closing as incompatible with current version and probably not needed anymore. If you think this is still the case in v2 then make PR for v2

**Pull request closed without merging**
