### PR TITLE
Fix getCurrentView

### LINKED ISSUE #3230: 4.4.5: $f7.views.current is undefined, (and some types are broken?)
* Framework7 version: v4.4.5
* Platform and Target: Chrome 75, Cordova Android 8.0

### Describe the bug
this.$f7.views.current is undefined

### To Reproduce
console.log(this.$f7.views.current.router)

### Expected behavior
this.$f7.views.current is not undefined
image

### Actual Behavior
Error in nextTick: "TypeError: Cannot read property 'router' of undefined"

### Screenshots
image

### Additional context
Works fine in all previous 4.* versions of Framework7.

**Also, some types are broken:**
image
image
image

(I'm not sure about types, maybe it just a WebStorm problem with Typescript support?)

### PR DESCRIPTION
**Pull request by NikitaKA**
This PR fixes #3230

### CODE REVIEW

**Comment by NikitaKA** [comment]
Maybe renaming the variable was planned? Anyway, that resolved my problem...

**Comment by nolimits4web** [comment]
Thanks, was a typo 👍

**Comment by NikitaKA** [comment]
> Thanks, was a typo 👍

I deep dive into that and found another solution:

```javascript
if ($viewEl.hasClass('tab')) {
      // Tabs
      $viewEl = $viewEl.filter((index, viewEl) => $(viewEl).hasClass('tab-active')).eq(0);
    } else {
      // Split View, leave appView intact
}
```

Or this is overkill? :D

**Comment by nolimits4web** [comment]
That is basically the same, with children lookup will be easier

**Pull request merged**
