### PR TITLE
Removed phonegap and added capacitor reference in package.json files

### PR DESCRIPTION
**Pull request by DAnn2012**
Remove phonegap reference from package.json files in packages folders (Core/React/Svelte/Vue)

### CODE REVIEW

**Comment by nolimits4web** [comment]
These are keywords, someone can still search by it, so `phonegap` must be there

**Comment by DAnn2012** [comment]
@nolimits4web 

and what do you think about adding `capacitor` as a keyword?

Thanks.

**Comment by nolimits4web** [comment]
@DAnn2012 I agree with adding `capacitor`

**Comment by DAnn2012** [comment]
@nolimits4web 

Done.

**Pull request merged**
