### PR TITLE
Update router.d.ts

### PR DESCRIPTION
**Pull request by jdspugh**
Allow Router.Component methods to have arguments, and events to have event and page arguments.

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/framework7io/framework7/blob/master/.github/CONTRIBUTING.md) when submitting a pull request.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Great, thanks 👍

**Comment by DAnn2012** [comment]
The change had to be made to the file

`framework7/src/core/modules/router/router.d.ts`

and not to the file

`packages/core/modules/router/router.d.ts`

Please @jdspugh you make this correction? Thank you.

**Comment by nolimits4web** [comment]
I pushed fix to `src`

**Comment by jdspugh** [comment]
Thanks. Just got back to this. Noted for next time.

**Pull request merged**
