### PR TITLE
Add `blured` class for navbar/toolbar

### PR DESCRIPTION
**Pull request by FWeinb**
In the iOS9/Safari9 it will be possible to have the blurred look introduced in iOS7 using `-webkit-backdrop-filter`. 
This PR will add basic support for this in the `.navbar` and `.toolbar`. I also modified photoBrowser.js to support a `blurred` option. The kitchen-sink demo is updated accordingly. 

[Here](https://www.youtube.com/watch?v=54MT0fSWO7w) is how it looks on an iPad running iOS9

### CODE REVIEW

**Comment by MarcGodard** [comment]
Awesome.

**Comment by nolimits4web** [comment]
Yes, finally they delivered something we can use :) I haven't installed yet to check that, but i am interesting about performance. On which iPad you did test it? Because i think to enable it by default for all bars and modals if it works smoothly on iPad 2

**Comment by FWeinb** [comment]
I only tested it on the latest iPad Air 2.

**Comment by evolutionjay** [comment]
Good job！

**Comment by zb0t** [comment]
The Apple website uses this effect as well.

background: rgba(255,255,255,.65),
-webkit-backdrop-filter: blur(20px) saturate(180%)

Works well

**Comment by chalchis** [comment]
someone
it has been tested on a mobile android

**Comment by ZanderBrown** [comment]
Could this be rebased and merged? There seems to be demand for this.

**Comment by valnub** [comment]
I agree, this would be a cool feature. Either this or #1040 should be merged if performance is good.

If it runs smoothly on mid-tier devices, it should be ok since devices are getting faster and faster in the future.

Let's say if it uns smoothly on iPhone 5s (or newer) and iPad Air (or newer), then it should be ok. They both run the Apple A7 chip and will still be supported by Apple in the next version of iOS while older devices might not.

But imho the feature should be **opt-in only**, so devs would have to flip `headerTranslucency:true` or sth like that in config if they're sure that they want to trade in translucency-effect for less performance.

By default, translucency should be turned off in my opinion.

**Comment by ZanderBrown** [comment]
@FWeinb are you aware this PR has merge conflicts?
It would be great if you could resolve those and consider @valnub 's points

**Comment by J05HI** [comment]
This isn't working on Chrome.

**Comment by ZanderBrown** [comment]
@J05HI we know, this is iOS/Safari ONLY.

**Comment by J05HI** [comment]
@ZanderBrown 
I've a solution in mind. 
I'll do a pull request if I have time.

**Comment by J05HI** [comment]
@nolimits4web @ZanderBrown 
Should be closed because it's not a good solution.

**Comment by ZanderBrown** [comment]
Reasoning?

**Comment by J05HI** [comment]
@ZanderBrown
Ios only compatibility

**Comment by ZanderBrown** [comment]
Their is no other way to implement this feature and for the iOS theme only having OSX/iOS comparability isn't a major issue.

And due to the way CSS is applied browsers​ that don't support it will display it as present albeit slightly transparent

**Comment by valnub** [comment]
What if we only add this to iOS stylesheet?

**Comment by nolimits4web** [comment]
Closing as incompatible with current version

**Pull request closed without merging**
