### PR TITLE
Update actions-class.js

### PR DESCRIPTION
**Pull request by zhennann**
maybe more extensible

### CODE REVIEW

**Comment by nolimits4web** [comment]
No, this is not needed. Actions already has same events as popover defined in popover's `on` settings

**Comment by zhennann** [comment]
If Actions showing as popover, the actions instance will donot known when the popover opened/closed. So need to emit the popoverOpened/Closed on Actions.

**Comment by nolimits4web** [comment]
These events already emitted here https://github.com/framework7io/framework7/blob/master/src/core/components/actions/actions-class.js#L108-L124

**Comment by zhennann** [comment]
wonderful，i see that

**Pull request closed without merging**
