### PR TITLE
Jalali Calendar and some other features for datepicker

### PR DESCRIPTION
**Pull request by sepehrr**
Hi
I created this PR for F7-v3. 
I added `minimumDaysInRange` and `maximumDaysInRange` when we use datepicker for selecting a range and I added support for jalali calendar by simply put `calendarType`:`jalali`
I put a simple jalali example on kitchen sink(s).

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks 👍 I'll try to review and merge it by the end of this week

**Comment by nolimits4web** [comment]
What i'm not sure about is that we have params override in constructor:
```js
if (params.calendarType === 'jalali') {
      params.monthNames = params.monthNames || ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'];
      params.monthNamesShort = params.monthNamesShort || ['فر', 'اد', 'خر', 'تیر', 'مر', 'شه', 'مهر', 'آب', 'آذر', 'دی', 'به', 'اس'];
      params.dayNames = params.dayNames || ['یک‌شنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنج‌شنبه', 'جمعه', 'شنبه'];
      params.dayNamesShort = params.dayNamesShort || ['1ش', '۲ش', '۳ش', '۴ش', '۵ش', 'ج', 'ش'];
      params.firstDay = params.firstDay || 6; // Saturday
      params.weekendDays = params.weekendDays || [5]; // Friday
    }
```

May be it would be better if we put them under `params.jalali` in calendar.js here? Like:
```js
...
jalali: {
  monthNames: ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'],
  monthNamesShort: ['فر', 'اد', 'خر', 'تیر', 'مر', 'شه', 'مهر', 'آب', 'آذر', 'دی', 'به', 'اس'],
  ...
},
...
```

What do you think?

**Comment by sepehrr** [comment]
Yes, That's a good idea, Thank you. I changed my code based on your suggestion.

**Comment by nolimits4web** [comment]
Awesome, thanks! 👍 💯 🔥 

I did super small refactoring at https://github.com/framework7io/framework7/commit/38fcf51972318981d10d9c525b5ca1f4c5777f1d

And renamed `minimumDaysInRange` and `maximumDaysInRange` params to `rangePickerMinDays` and `rangePickerMaxDays`

**Pull request merged**
