### PR TITLE
suggestions for review

### PR DESCRIPTION
**Pull request by JasonKleban**
I think these are right - they correct the errors for my own test project.

### CODE REVIEW

**Comment by JasonKleban** [comment]
I see some of the fixes in those other PRs, but still missing `import * as React from 'react';` and the `declare` keyword on the namespaces and classes in the .d.ts?  No?

**Comment by nolimits4web** [comment]
@JasonKleban @dlee thanks guys! You almost sent these fixes simultaneously 👍 Because typings are generated automatically by phenome I have updated phenome and main d.ts build script. I ask you to get latest repo, npm install, and run `npm run build-react:dev` and check typings in build folder. If everything is ok I’ll do the release

**Comment by nolimits4web** [comment]
@JasonKleban after running build command, you should see output in build/react/ folder. All you mention should be there

**Comment by nolimits4web** [comment]
And make sure you call npm install to get latest phenome

**Comment by JasonKleban** [comment]
Ok great!  I won't be able to verify for at least 8 hours - in case you're itching to release.

**Comment by dlee** [comment]
Looks good to me

**Comment by nolimits4web** [comment]
Will do the release tomorrow

**Comment by JasonKleban** [comment]
What branch?  master seems to have many problems to me

**Pull request closed without merging**
