### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by Jason-Cooke**

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hello @Jason-Cooke  ,

Can you please make a similar change in the last line of this file of another Repo:

https://github.com/framework7io/framework7-website/blob/master/README.md

I thank you in advance.

**Comment by Jason-Cooke** [comment]
Hi @DAnn2012 

Yes certainly!

Heres the PR: https://github.com/framework7io/framework7-website/pull/337

**Comment by nolimits4web** [comment]
Thanks!

**Comment by Jason-Cooke** [comment]
My pleasure!

**Pull request merged**
