### PR TITLE
fix: add closeByOutsideClick, not handle button click if action.group…

### PR DESCRIPTION
**Pull request by zhennann**
1. add closeByOutsideClick
2. not handle button click if action.groups not specified in framework7-vue

### CODE REVIEW

**Comment by nolimits4web** [comment]
Looks good, but why there is a `if (actions.groups) {` condition added?

**Comment by zhennann** [comment]
1. In framework7-vue, not given the parameter `groups` to actions component.

```
<f7-actions ref="actionsOneGroup">
      <f7-actions-group>
        <f7-actions-label>Do something</f7-actions-label>
        <f7-actions-button bold>Button 1</f7-actions-button>
        <f7-actions-button>Button 2</f7-actions-button>
        <f7-actions-button color="red">Cancel</f7-actions-button>
      </f7-actions-group>
    </f7-actions>
```
2. While, in framework7, actions-class.js handle events of buttons.
```
actions.$el.find('.actions-button').each((groupIndex, buttonEl) => {
    **$(buttonEl).on('click', buttonOnClick);**
});
```
3. Then,the variable 'groups' in buttonOnClick will be undefined.
```
function buttonOnClick(e) {
      const buttonEl = this;
      let buttonIndex;
      let groupIndex;
      if ($(buttonEl).hasClass('item-link')) {
        buttonIndex = $(buttonEl).parents('li').index();
        groupIndex = $(buttonEl).parents('.list').index();
      } else {
        buttonIndex = $(buttonEl).index();
        groupIndex = $(buttonEl).parents('.actions-group').index();
      }
      **const button = groups[groupIndex][buttonIndex];**
      if (button.onClick) button.onClick(actions, e);
      if (actions.params.onClick) actions.params.onClick(actions, e);
      if (button.close !== false) actions.close();
}
```

**Comment by nolimits4web** [comment]
I see, the we need it only around lines 125-134, because the same condition for `popoverOpened` and `popoverClosed` events doesn't make sense, because it is for conversion to popover which won't happen anyway if we don't pass buttons/groups parameter. Can you remove it there and i will merge it?

**Comment by nolimits4web** [comment]
Thanks, merged!

**Comment by zhennann** [comment]
With pleasure!

**Pull request merged**
