### PR TITLE
Update material-tabbar.js

### PR DESCRIPTION
**Pull request by jirawat001**
change var in if else for codingstandard

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Why?

**Comment by jirawat001** [comment]
read for simplify and  well-ordered

**Comment by ZanderBrown** [comment]
> Why?

**Comment by jirawat001** [comment]
I Not understand question?

**Comment by ZanderBrown** [comment]
You have moved around some indentation and stored the result of a boolean operation in a variable with the only comment being 'coding style', I asked for further explanation to which you essentially repeated your initial statement.

Please explain why (potentially with references) you have made these modifications.

**Comment by jirawat001** [comment]
for some programmer  to understand to if else have duty to work.Sorry if answer is not correct

**Comment by ZanderBrown** [comment]
You haven't been able to justify this alteration and it doesn't fix any bug

**Pull request closed without merging**
