### PR TITLE
secure all urls

### PR DESCRIPTION
**Pull request by scriptPilot**
All urls checked before if SSL is possible. This will avoid warnings in
some web browsers!

### CODE REVIEW

**Comment by ZanderBrown** [comment]
How about `//`ing all the things

**Comment by scriptPilot** [comment]
@ZanderBrown - What do you mean?

**Comment by ZanderBrown** [comment]
[`//` Magic](https://www.paulirish.com/2010/the-protocol-relative-url/)

**Comment by scriptPilot** [comment]
@ZanderBrown - Thanks, I updated all src files accordingly!

**Comment by valnub** [comment]
Well done, how can we check if all url's have been changed and nothing broke?

**Comment by valnub** [comment]
Hold on a sec, the changes seem to be made for xmlns:

`<svg xmlns='//w3.org/2000/svg'`

Is this really necessary? I don't think that the browser actually calls these url's. They're just namespaces.

**Comment by nolimits4web** [comment]
Closing as incompatible with current version and probably not needed anymore

**Pull request closed without merging**
