### PR TITLE
Issue #2379

### PR DESCRIPTION
**Pull request by chachew**
Fix js error when calling app.panel.disableSwipe('left'); OR app.panel.disableSwipe('right');

This fixes the javascript errors that are thrown when trying to call app.panel.disableSwipe('left') OR app.panel.disableSwipe('right');

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks, but this need to be done for `src` files only:

https://github.com/framework7io/framework7#contributing

> All changes should be commited to src/ files.

**Comment by chachew** [comment]
Sorry, fixed that.

**Comment by nolimits4web** [comment]
Changes to `dist/` file should be removed

**Comment by nolimits4web** [comment]
Thanks 👍

**Pull request merged**
