### PR TITLE
Run <script>s in loaded pages

### LINKED ISSUE #70: Trig Javascript in .html file after loading page.
Hello!
When you click on a link, an Ajax call is done and the page is loaded. But in this page, there is Javascript content that can trigger external libraries' content like Highcharts for example.

Are there any way to use Javascript in .html file after an Ajax call loading page ?

Thanks for your Framework!
CloudCompany

### PR DESCRIPTION
**Pull request by eslindsey**
Enhancement that fixes #70

### CODE REVIEW

**Comment by eslindsey** [comment]
This enhancement now allows an optional, case-insensitive `data-run` attribute on the `SCRIPT` tag, which determines when that script is executed. All page callback values are allowed: `beforeInit`, `init`, `reinit`, `beforeAnimation`, `afterAnimation`, `back`, `afterBack`, `beforeRemove`. If `data-run` is not provided, it defaults to `init`.

**Comment by eslindsey** [comment]
Note that defining functions within inline scripts executed in this method does not work quite as expected. Instead of writing:
```javascript
function myFunctionHere() {
    //...
}
```
You must define the function in the style of a variable:
```javascript
window.myFunctionHere = function() {
    //...
}
```

**Comment by ZanderBrown** [comment]
Not sure about the use of eval, perhaps use new Function or a data uri?

**Comment by lbrawnbrawny** [comment]
good

**Comment by nolimits4web** [comment]
Closing as incompatible with current version and probably not needed anymore. If you think this is still the case in v2 then make PR for v2

**Pull request closed without merging**
